### ISSUE TITLE
Ability to call marker with exact tag

### ISSUE THREAD

**Issue by armpogart** [bmacnaughton/gulp-markers#1]
First thanks for the great plugin. I started using it instead of all other replacement plugins as it gives more control.

Would you be so kind to add ability to call `replaceMarkers(tag)` with exact tag. I currently have gulp task that does very similar replacement, first for publishing files to tmp directory from where they're served and then to publish to distribution directory with another replacement. I need to setup to markers objects currently and I see no use for `tag` key, it would be great to setup just one object with 2 different tags and call `replaceMarkers` with tag specified and as I'm doing very similar thing, just checking the tag in my replace function would be enough to do the appropriate thing in both cases.

If you are busy and give this feature a go, and would like me to do the PR, please let me know.
Thanks again.

**Comment by armpogart** [comment]
On the second though, if you think that `tag` is intended to be used another way (though I don't get what's the purpose of tag), you can just expose some data passing through `replaceMarkers` which will be available to `replace` function through `context`.

**EDIT:** Now I see what's the purpose of tag, and I would propose to pass data to `replace` function through `replaceMarkers`.

**Comment by bmacnaughton** [comment]
Sorry for the slow reply - I have been heads down with a time-sensitive project and didn't see this.

I'm glad you find the package useful - thanks for letting me know.

`tag` is "just" a name but is also context. It is passed to the `replace` function in the `context`, as you've seen.

The code in `addMarker()` accepts an options argument which can have a `data` property. This will be passed to the `replace` function in the `context` object (first argument to the `replace` function). So it is possible to pass data to the `replace` function. But it doesn't sound like that is what you're looking for.

If the issue is that you don't have the information you need when you call `addMarker()` but you do have it when you call `replaceMarkers()` one alternative is to just pass an empty object to `addMarker()` and then modify it before calling `replaceMarkers()`. `addMarker()` just stores the object - it doesn't copy it - so you can modify it before calling `replaceMarkers()`.

something like:

```javascript
Markers = require('gulp-markers');

var markers = new Markers();

var dataNeededForReplace = {};

markers.addMarker({
    tag: 'js-insertions',
    re: /<!-- @insert:js-vendor -->/,
    replace: function(context, match) {
        var vendorJSFiles = ['jquery.min.js', 'paper-core.min.js'];
        var lines = vendorJSFiles.map(f => '<script src="' + f + '"></script>');
        return lines.join('\n');
    },
    opts: {
        data: dataNeededForReplace
    }
});

// get info needed
dataNeededForReplace.info = 'important string';
dataNeededForReplace.count = 42;

// the object will be passed in context as context.data to the replace function.
```

If that doesn't help maybe you could give me a little more of an idea what you are trying to do?

**Comment by bmacnaughton** [comment]
I'm closing this because I haven't heard back and that usually means things are working. If not, let me know and I'm happy to reopen the issue.
